# Generated by Django 3.2.9 on 2021-11-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
